sudo: true
before_install:

# Decrypt Server Key
- openssl aes-256-cbc -K $encrypted_79a2f6093848_key -iv $encrypted_79a2f6093848_iv -in assets/server.key.enc -out assets/server.key -d

# Assign variables
- export CLIURL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz  
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG

# Create sfdx dir
- mkdir sfdx

# Install Salesforce CLI
- wget -qO- $CLIURL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH

before_script:
#
# The before_script step initializes varibles used in the script step
#

#Assign variables
- export DEPLOYDIR=src
- export TESTLEVEL=RunLocalTests
- sfdx --version
- sfdx plugins --core

script:
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setalias UAT

#- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg --wait
#  3
#- sfdx force:org:display -u ciorg
#- sfdx force:source:push -u ciorg
#- sfdx force:apex:test:run -u ciorg --wait 10
#- sfdx force:org:delete -u ciorg -p
